# Generated by Django 5.0.1 on 2026-02-01 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('stakes', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('position', models.TextField(help_text='Current position or thesis')),
                ('confidence', models.FloatField(blank=True, help_text='Confidence level 0.0-1.0', null=True)),
                ('created_from_event_id', models.UUIDField(help_text='Event that triggered case creation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('case_brief', 'Case Brief'), ('inquiry_brief', 'Inquiry Brief'), ('research', 'Research Report'), ('debate', 'AI Debate'), ('critique', 'AI Critique'), ('source', 'Source Document'), ('notes', 'Notes')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('content_markdown', models.TextField(default='', help_text='Document content in markdown')),
                ('edit_friction', models.CharField(choices=[('low', 'Easy to edit'), ('high', 'Annotate only'), ('readonly', 'Read-only')], help_text='Edit permission level', max_length=20)),
                ('ai_structure', models.JSONField(default=dict, help_text='Extracted structure - research has findings, debates have positions, etc.')),
                ('generated_by_ai', models.BooleanField(default=False, help_text='Whether this document was AI-generated')),
                ('agent_type', models.CharField(blank=True, help_text='Type of agent that generated this (research, debate, critique)', max_length=50)),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt used to generate this document')),
                ('times_cited', models.IntegerField(default=0, help_text='How many times this document is cited by others')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_text', models.TextField(help_text='The [[link]] text as it appears in document')),
                ('line_number', models.IntegerField(blank=True, help_text='Line number in source document', null=True)),
                ('cited_section', models.CharField(blank=True, help_text="Section anchor (e.g., 'findings', 'conclusion')", max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_json', models.JSONField(help_text='Materialized case state with signals')),
                ('based_on_event_id', models.UUIDField(help_text='Last event included in this snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
