# Generated by Django 5.0.1 on 2026-02-01 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('chat', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='linked_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_cases', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this case belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='projects.project'),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_case_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
