# Generated by Django 5.0.1 on 2026-02-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='inquiry',
            field=models.ForeignKey(blank=True, help_text='If document is specific to an inquiry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_documents', to='inquiries.inquiry'),
        ),
        migrations.AddField(
            model_name='case',
            name='main_brief',
            field=models.ForeignKey(blank=True, help_text='Main case brief document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_main_brief_for', to='cases.casedocument'),
        ),
        migrations.AddField(
            model_name='documentcitation',
            name='from_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_citations', to='cases.casedocument'),
        ),
        migrations.AddField(
            model_name='documentcitation',
            name='to_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_citations', to='cases.casedocument'),
        ),
        migrations.AddField(
            model_name='workingview',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_views', to='cases.case'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['case', 'document_type'], name='cases_cased_case_id_f9271c_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['inquiry', 'document_type'], name='cases_cased_inquiry_8cba40_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['case', '-created_at'], name='cases_cased_case_id_d5d10c_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['created_by', '-created_at'], name='cases_cased_created_b9dde8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user', '-updated_at'], name='cases_case_user_id_ccbb71_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['project', '-updated_at'], name='cases_case_project_b7ef73_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-updated_at'], name='cases_case_status_d3ae0d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['linked_thread', '-created_at'], name='cases_case_linked__841724_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcitation',
            index=models.Index(fields=['from_document', '-created_at'], name='cases_docum_from_do_6212e7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcitation',
            index=models.Index(fields=['to_document', '-created_at'], name='cases_docum_to_docu_58cfdf_idx'),
        ),
        migrations.AddIndex(
            model_name='workingview',
            index=models.Index(fields=['case', '-created_at'], name='cases_worki_case_id_c6bcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='workingview',
            index=models.Index(fields=['based_on_event_id'], name='cases_worki_based_o_d35c4c_idx'),
        ),
    ]
