# Generated by Django 5.0.1 on 2026-02-01 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='active_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills activated for this case', related_name='active_in_cases', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='case',
            name='based_on_skill',
            field=models.ForeignKey(blank=True, help_text='Skill this case was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_cases', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='case',
            name='became_skill',
            field=models.OneToOneField(blank=True, help_text='Skill created from this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_case', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_skill_template',
            field=models.BooleanField(default=False, help_text='Whether this case is being used as a skill template'),
        ),
        migrations.AddField(
            model_name='case',
            name='template_scope',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('team', 'Team'), ('organization', 'Organization')], help_text='Scope if this case is a skill template', max_length=20, null=True),
        ),
    ]
