# Generated by Django 5.0.1 on 2026-02-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_user_confidence_and_checklist"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="readinesschecklistitem",
            new_name="cases_readi_case_id_007e00_idx",
            old_name="cases_readi_case_id_6c9c8a_idx",
        ),
        migrations.AddField(
            model_name="readinesschecklistitem",
            name="completion_note",
            field=models.TextField(
                blank=True,
                help_text="Note about how/why this was completed (especially for auto-completion)",
            ),
        ),
        migrations.AddField(
            model_name="readinesschecklistitem",
            name="created_by_ai",
            field=models.BooleanField(
                default=False, help_text="Whether this item was AI-generated"
            ),
        ),
        migrations.AddField(
            model_name="readinesschecklistitem",
            name="why_important",
            field=models.TextField(
                blank=True,
                help_text="AI explanation of why this item matters for the decision",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence level 0.0-1.0 (DEPRECATED - use user_confidence)",
                null=True,
            ),
        ),
    ]
