# Generated by Django 5.0.1 on 2026-02-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0008_rename_cases_readi_case_id_6c9c8a_idx_cases_readi_case_id_007e00_idx_and_more",
        ),
        ("inquiries", "0002_inquiry_blocked_by"),
        ("signals", "0002_add_composite_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readinesschecklistitem",
            options={"ordering": ["parent__order", "order", "id"]},
        ),
        migrations.AddField(
            model_name="readinesschecklistitem",
            name="blocks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Items that cannot be completed until this one is done",
                related_name="blocked_by",
                to="cases.readinesschecklistitem",
            ),
        ),
        migrations.AddField(
            model_name="readinesschecklistitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("validation", "Validate Assumption"),
                    ("investigation", "Complete Investigation"),
                    ("analysis", "Perform Analysis"),
                    ("stakeholder", "Stakeholder Input"),
                    ("alternative", "Evaluate Alternative"),
                    ("criteria", "Define Criteria"),
                    ("custom", "Custom"),
                ],
                default="custom",
                help_text="Type of readiness item",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="readinesschecklistitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent item (for nested/dependent items)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="cases.readinesschecklistitem",
            ),
        ),
        migrations.AddIndex(
            model_name="readinesschecklistitem",
            index=models.Index(
                fields=["case", "parent"], name="cases_readi_case_id_61d485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readinesschecklistitem",
            index=models.Index(
                fields=["item_type"], name="cases_readi_item_ty_3b74c7_idx"
            ),
        ),
    ]
