# Generated by Django 5.0.1 on 2026-02-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_add_embedding_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="confidence",
        ),
    ]
