# Generated by Django 5.0.1 on 2026-02-06 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_remove_deprecated_confidence_field'),
        ('inquiries', '0003_add_embedding_field'),
        ('signals', '0002_add_composite_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.CharField(db_index=True, help_text='Matches <!-- section:ID --> marker in markdown', max_length=100)),
                ('heading', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('section_type', models.CharField(choices=[('decision_frame', 'Decision Frame'), ('inquiry_brief', 'Inquiry Brief'), ('synthesis', 'Synthesis'), ('trade_offs', 'Trade-offs'), ('recommendation', 'Recommendation'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('depth', models.IntegerField(default=0, help_text='0 = top-level, 1 = subsection, 2 = sub-sub')),
                ('created_by', models.CharField(choices=[('system', 'System scaffolded'), ('user', 'User created'), ('agent', 'Agent suggested')], default='system', max_length=20)),
                ('is_linked', models.BooleanField(default=False, help_text='True if linked to inquiry or has tagged signals')),
                ('grounding_status', models.CharField(choices=[('empty', 'No evidence yet'), ('weak', 'Under-evidenced'), ('moderate', 'Some evidence'), ('strong', 'Well-grounded'), ('conflicted', 'Has unresolved tensions')], default='empty', max_length=20)),
                ('grounding_data', models.JSONField(blank=True, default=dict, help_text='Cached grounding metrics: evidence_count, tensions_count, etc.')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked sections show lock_reason instead of edit controls')),
                ('lock_reason', models.CharField(blank=True, help_text='e.g. "Resolve 2 tensions to unlock"', max_length=200)),
                ('is_collapsed', models.BooleanField(default=False, help_text='User preference for collapsed/expanded state')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_sections', to='cases.casedocument')),
                ('inquiry', models.ForeignKey(blank=True, help_text='Links this section to an inquiry for grounding computation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brief_sections', to='inquiries.inquiry')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='cases.briefsection')),
                ('tagged_signals', models.ManyToManyField(blank=True, related_name='tagged_in_sections', to='signals.signal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BriefAnnotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation_type', models.CharField(choices=[('tension', 'Sources disagree'), ('blind_spot', 'Missing analysis'), ('ungrounded', 'Unvalidated assumption'), ('evidence_desert', 'Needs more evidence'), ('well_grounded', 'Strong evidence'), ('stale', 'Evidence may be outdated'), ('circular', 'Circular reasoning detected')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the annotation')),
                ('priority', models.CharField(choices=[('blocking', 'Blocking'), ('important', 'Important'), ('info', 'Informational')], default='important', max_length=20)),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='When the user dismissed this annotation', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this annotation was resolved', null=True)),
                ('resolved_by', models.CharField(blank=True, help_text='user, system, or agent', max_length=50)),
                ('source_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brief_annotations', to='inquiries.inquiry')),
                ('source_signals', models.ManyToManyField(blank=True, related_name='brief_annotations', to='signals.signal')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cases.briefsection')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='briefsection',
            index=models.Index(fields=['brief', 'order'], name='cases_brief_brief_i_7af1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='briefsection',
            index=models.Index(fields=['brief', 'section_type'], name='cases_brief_brief_i_1d677f_idx'),
        ),
        migrations.AddIndex(
            model_name='briefsection',
            index=models.Index(fields=['inquiry'], name='cases_brief_inquiry_4055c8_idx'),
        ),
        migrations.AddIndex(
            model_name='briefannotation',
            index=models.Index(fields=['section', 'annotation_type'], name='cases_brief_section_cced27_idx'),
        ),
        migrations.AddIndex(
            model_name='briefannotation',
            index=models.Index(fields=['section', 'dismissed_at'], name='cases_brief_section_7ef3b0_idx'),
        ),
    ]
