# Generated by Django 5.0.1 on 2026-02-07 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_briefsection_briefannotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseDocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(help_text="Sequential version number")),
                (
                    "content_markdown",
                    models.TextField(help_text="Full document content at this version"),
                ),
                (
                    "diff_summary",
                    models.TextField(
                        blank=True, help_text="Human-readable summary of what changed"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("ai_suggestion", "AI Suggestion"),
                            ("ai_task", "AI Agentic Task"),
                            ("auto_save", "Auto-save"),
                            ("restore", "Restored from version"),
                        ],
                        help_text="Who/what created this version",
                        max_length=30,
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        blank=True,
                        help_text="If AI-generated, the task/prompt that triggered the edit",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cases.casedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["document", "-version"],
                        name="cases_cased_documen_6d13a6_idx",
                    ),
                    models.Index(
                        fields=["document", "-created_at"],
                        name="cases_cased_documen_0a7013_idx",
                    ),
                ],
                "unique_together": {("document", "version")},
            },
        ),
    ]
