# Generated by Django 5.0.1 on 2026-02-07 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_add_casedocumentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('exploring', 'Exploring'), ('investigating', 'Investigating'), ('synthesizing', 'Synthesizing'), ('ready', 'Ready')], default='exploring', help_text='Current investigation stage', max_length=20)),
                ('current_version', models.IntegerField(default=1, help_text='Latest accepted version number')),
                ('position_statement', models.TextField(blank=True, help_text='Current working thesis — evolves with evidence')),
                ('created_from_event_id', models.UUIDField(blank=True, help_text='Event that triggered plan creation', null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(help_text='Sequential version number')),
                ('content', models.JSONField(help_text='Full plan snapshot — phases, assumptions, decision_criteria')),
                ('diff_summary', models.TextField(blank=True, help_text='Human-readable summary of what changed')),
                ('diff_data', models.JSONField(blank=True, help_text='Structured diff for UI rendering (added/removed/changed items)', null=True)),
                ('created_by', models.CharField(choices=[('system', 'System (initial generation)'), ('ai_proposal', 'AI Proposal (accepted by user)'), ('user_request', 'User Request (via chat)'), ('critique', 'Critique Agent'), ('restore', 'Restored from previous version')], help_text='Who/what created this version', max_length=30)),
                ('created_from_event_id', models.UUIDField(blank=True, help_text='Event that triggered this version', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cases.investigationplan')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='investigationplan',
            index=models.Index(fields=['case'], name='cases_inves_case_id_7f17fa_idx'),
        ),
        migrations.AddIndex(
            model_name='planversion',
            index=models.Index(fields=['plan', '-version_number'], name='cases_planv_plan_id_f46e94_idx'),
        ),
        migrations.AddIndex(
            model_name='planversion',
            index=models.Index(fields=['plan', '-created_at'], name='cases_planv_plan_id_16d9b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together={('plan', 'version_number')},
        ),
    ]
