# Generated by Django 5.0.1 on 2026-02-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_case_intelligence_investigation_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseActiveSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Priority order (lower = higher priority)"
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "case_active_skills",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="briefannotation",
            name="annotation_type",
            field=models.CharField(
                choices=[
                    ("tension", "Sources disagree"),
                    ("blind_spot", "Missing analysis"),
                    ("ungrounded", "Unvalidated assumption"),
                    ("evidence_desert", "Needs more evidence"),
                    ("well_grounded", "Strong evidence"),
                    ("stale", "Evidence may be outdated"),
                    ("circular", "Circular reasoning detected"),
                    ("low_credibility", "Relies on low-credibility evidence"),
                ],
                max_length=30,
            ),
        ),
    ]
