# Generated by Django 5.0.1 on 2026-02-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_skill_packs_and_ordered_active_skills"),
        ("skills", "0003_skill_packs_and_ordered_active_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseactiveskill",
            name="activated_from_pack",
            field=models.ForeignKey(
                blank=True,
                help_text="Pack that caused this activation (for provenance)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="skills.skillpack",
            ),
        ),
        migrations.AddField(
            model_name="caseactiveskill",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cases.case"
            ),
        ),
        migrations.AddField(
            model_name="caseactiveskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skills.skill"
            ),
        ),
        migrations.RemoveField(
            model_name="case",
            name="active_skills",
        ),
        migrations.AddField(
            model_name="case",
            name="active_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills activated for this case (ordered)",
                related_name="active_in_cases",
                through="cases.CaseActiveSkill",
                to="skills.skill",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="caseactiveskill",
            unique_together={("case", "skill")},
        ),
    ]
