# Generated by Django 5.0.1 on 2026-02-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_skill_packs_and_ordered_active_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workingview",
            name="case",
        ),
        migrations.RemoveField(
            model_name="case",
            name="what_changed_mind_response",
        ),
        migrations.RemoveField(
            model_name="case",
            name="what_changed_mind_response_at",
        ),
        migrations.RemoveField(
            model_name="caseactiveskill",
            name="activated_from_pack",
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="agent_type",
            field=models.CharField(
                blank=True,
                help_text="Type of agent that generated this (e.g. research)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="ai_structure",
            field=models.JSONField(
                default=dict,
                help_text="Extracted structure - e.g. research has findings",
            ),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("case_brief", "Case Brief"),
                    ("inquiry_brief", "Inquiry Brief"),
                    ("research", "Research Report"),
                    ("source", "Source Document"),
                    ("notes", "Notes"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="ReadinessChecklistItem",
        ),
        migrations.DeleteModel(
            name="WorkingView",
        ),
    ]
