# Generated by Django 5.0.1 on 2026-02-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_remove_workingview_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefsection',
            name='is_linked',
            field=models.BooleanField(default=False, help_text='True if linked to inquiry'),
        ),
    ]
