# Generated by Django 5.0.1 on 2026-02-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_case_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workingdocument',
            new_name='cases_worki_case_id_f8b865_idx',
            old_name='cases_cased_case_id_f9271c_idx',
        ),
        migrations.RenameIndex(
            model_name='workingdocument',
            new_name='cases_worki_inquiry_80547c_idx',
            old_name='cases_cased_inquiry_8cba40_idx',
        ),
        migrations.RenameIndex(
            model_name='workingdocument',
            new_name='cases_worki_case_id_64489b_idx',
            old_name='cases_cased_case_id_d5d10c_idx',
        ),
        migrations.RenameIndex(
            model_name='workingdocument',
            new_name='cases_worki_created_ab7293_idx',
            old_name='cases_cased_created_b9dde8_idx',
        ),
        migrations.RenameIndex(
            model_name='workingdocumentversion',
            new_name='cases_worki_documen_07936a_idx',
            old_name='cases_cased_documen_6d13a6_idx',
        ),
        migrations.RenameIndex(
            model_name='workingdocumentversion',
            new_name='cases_worki_documen_3bad50_idx',
            old_name='cases_cased_documen_0a7013_idx',
        ),
    ]
