# Generated by Django 5.0.1 on 2026-02-12 18:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_clusterhierarchy_projectinsight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("decided", "Decided"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DecisionRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision_text",
                    models.TextField(
                        help_text="What was decided — the actual decision statement"
                    ),
                ),
                (
                    "key_reasons",
                    models.JSONField(
                        default=list,
                        help_text="List of reason strings: why this decision was made",
                    ),
                ),
                (
                    "confidence_level",
                    models.IntegerField(
                        help_text="Decision confidence 0-100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "caveats",
                    models.TextField(
                        blank=True,
                        help_text="Known risks, conditions, or things to watch for",
                    ),
                ),
                (
                    "linked_assumption_ids",
                    models.JSONField(
                        default=list,
                        help_text="UUIDs of assumptions the user marked as validated during decision",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the decision was formally recorded",
                    ),
                ),
                (
                    "outcome_check_date",
                    models.DateField(
                        blank=True,
                        help_text="When to check back on how the decision played out",
                        null=True,
                    ),
                ),
                (
                    "outcome_notes",
                    models.JSONField(
                        default=list,
                        help_text="List of outcome observations: [{date, note, sentiment}]",
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["case"], name="cases_decis_case_id_b64781_idx"
                    ),
                    models.Index(
                        fields=["outcome_check_date"],
                        name="cases_decis_outcome_00a5d4_idx",
                    ),
                ],
            },
        ),
    ]
