# Generated by Django 5.0.1 on 2026-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_alter_case_status_decisionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='planversion',
            name='generation_context',
            field=models.JSONField(blank=True, default=dict, help_text='Context that influenced this version: thread_id, message excerpt, research results, etc.'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('initial', 'Initial generation'), ('user_edit', 'User manual edit'), ('chat_edit', 'Chat-based edit'), ('ai_proposal_accepted', 'AI proposal accepted'), ('extraction_complete', 'Extraction pipeline'), ('research_complete', 'Research complete'), ('document_added', 'Document added'), ('regeneration', 'Plan regeneration'), ('stage_change', 'Stage change'), ('restore', 'Version restore')], default='initial', help_text='What triggered this version creation', max_length=30),
        ),
    ]
