# Generated by Django 5.0.1 on 2026-02-02 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_rename_chat_messag_content_idx_chat_messag_content_dc73a7_idx'),
        ('events', '0003_alter_event_type'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(help_text='Confidence level at this point in time (0.0-1.0)')),
                ('reason', models.TextField(blank=True, help_text='Human-readable explanation for the change')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this confidence level was recorded')),
                ('inquiry', models.ForeignKey(help_text='Inquiry being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='confidence_history', to='inquiries.inquiry')),
                ('trigger_event', models.ForeignKey(blank=True, help_text='Event that caused this confidence change', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'verbose_name_plural': 'inquiry histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['inquiry', '-timestamp'], name='companion_i_inquiry_9456e1_idx'), models.Index(fields=['timestamp'], name='companion_i_timesta_f8a0de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reflection_text', models.TextField(help_text='Natural language meta-commentary (2-3 paragraphs)')),
                ('trigger_type', models.CharField(choices=[('user_message', 'User Message'), ('document_upload', 'Document Upload'), ('contradiction_detected', 'Contradiction Detected'), ('periodic', 'Periodic Reflection'), ('confidence_change', 'Confidence Change')], help_text='What event triggered this reflection', max_length=50)),
                ('analyzed_messages', models.JSONField(default=list, help_text='List of message IDs that were analyzed')),
                ('analyzed_signals', models.JSONField(default=list, help_text='List of signal IDs that were considered')),
                ('patterns', models.JSONField(blank=True, default=dict, help_text='Graph patterns identified (ungrounded, contradictions, etc.)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether to show in companion panel')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When user last viewed this reflection', null=True)),
                ('thread', models.ForeignKey(help_text='Thread this reflection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='chat.chatthread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread', '-created_at'], name='companion_r_thread__bc4e16_idx'), models.Index(fields=['thread', 'is_visible', '-created_at'], name='companion_r_thread__3fc95b_idx'), models.Index(fields=['trigger_type', '-created_at'], name='companion_r_trigger_2ba618_idx')],
            },
        ),
    ]
