# Generated by Django 5.0.1 on 2026-02-01 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_initial'),
        ('chat', '0001_initial'),
        ('events', '0001_initial'),
        ('inquiries', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('chat_message', 'Chat Message'), ('document', 'Document'), ('artifact', 'Artifact'), ('analysis', 'Analysis')], default='chat_message', max_length=20)),
                ('type', models.CharField(choices=[('DecisionIntent', 'Decision Intent'), ('Claim', 'Claim'), ('Goal', 'Goal'), ('Constraint', 'Constraint'), ('Assumption', 'Assumption'), ('Question', 'Question'), ('EvidenceMention', 'Evidence Mention')], db_index=True, max_length=50)),
                ('text', models.TextField(help_text='Original extracted text')),
                ('normalized_text', models.TextField(help_text='Normalized for comparison')),
                ('span', models.JSONField(default=dict, help_text='Location info: {message_id, start, end}')),
                ('confidence', models.FloatField(help_text='Extraction confidence 0.0-1.0')),
                ('sequence_index', models.IntegerField(help_text='Message position in thread (0, 1, 2...)')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='If user marked this signal as not relevant', null=True)),
                ('temperature', models.CharField(choices=[('hot', 'Hot (Always in Context)'), ('warm', 'Warm (Retrieved on Demand)'), ('cold', 'Cold (Archival)')], db_index=True, default='warm', help_text='Memory tier - hot=always loaded, warm=retrieved, cold=archival', max_length=10)),
                ('access_count', models.IntegerField(default=0, help_text='How many times this signal was retrieved for context')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time this signal was included in LLM context', null=True)),
                ('pinned_at', models.DateTimeField(blank=True, help_text='User pinned this signal to always include in context', null=True)),
                ('embedding', models.JSONField(blank=True, help_text='Semantic embedding vector (384 or 768 dim from sentence-transformers)', null=True)),
                ('dedupe_key', models.CharField(db_index=True, help_text='Hash for exact-match deduplication', max_length=64)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='cases.case')),
                ('contradicts', models.ManyToManyField(blank=True, help_text='Signals this signal contradicts', related_name='contradicted_by', to='signals.signal')),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Signals this signal depends on (assumption chains)', related_name='dependents', to='signals.signal')),
                ('document', models.ForeignKey(blank=True, help_text='If extracted from a document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='projects.document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='events.event')),
                ('inquiry', models.ForeignKey(blank=True, help_text='If this signal was elevated to or associated with an inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_signals', to='inquiries.inquiry')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='chat.chatthread')),
            ],
            options={
                'ordering': ['sequence_index', '-created_at'],
                'indexes': [models.Index(fields=['case', 'type'], name='signals_sig_case_id_c28d88_idx'), models.Index(fields=['thread', 'sequence_index'], name='signals_sig_thread__2d1469_idx'), models.Index(fields=['document', 'sequence_index'], name='signals_sig_documen_744a14_idx'), models.Index(fields=['case', 'type', 'sequence_index'], name='signals_sig_case_id_89cf38_idx'), models.Index(fields=['source_type', 'created_at'], name='signals_sig_source__402bc2_idx'), models.Index(fields=['dedupe_key', 'case'], name='signals_sig_dedupe__d8e52d_idx'), models.Index(fields=['inquiry', 'created_at'], name='signals_sig_inquiry_d69145_idx'), models.Index(fields=['dismissed_at'], name='signals_sig_dismiss_8cde6e_idx'), models.Index(fields=['temperature', 'case'], name='signals_sig_tempera_2142dd_idx'), models.Index(fields=['thread', 'temperature'], name='signals_sig_thread__da11d1_idx'), models.Index(fields=['access_count', 'last_accessed'], name='signals_sig_access__aeb012_idx')],
            },
        ),
    ]
