# Generated by Django 5.0.1 on 2026-02-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_active_skills_case_based_on_skill_and_more'),
        ('chat', '0002_chatthread_last_agent_check_at_and_more'),
        ('events', '0003_alter_event_type'),
        ('inquiries', '0001_initial'),
        ('projects', '0002_add_evidence_signal_links'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['thread', 'dismissed_at', 'sequence_index'], name='signals_sig_thread__5f174d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['case', 'dismissed_at', 'created_at'], name='signals_sig_case_id_9c6beb_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['thread', 'dismissed_at', 'type'], name='signals_sig_thread__640dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['case', 'dismissed_at', 'type'], name='signals_sig_case_id_94a478_idx'),
        ),
    ]
