# Generated by Django 5.0.1 on 2026-02-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signal_assumption_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signal',
            new_name='signals_sig_case_id_3b5a33_idx',
            old_name='signals_sig_case_id_assum_idx',
        ),
        migrations.AlterField(
            model_name='signal',
            name='source_type',
            field=models.CharField(choices=[('chat_message', 'Chat Message'), ('document', 'Document'), ('artifact', 'Artifact'), ('analysis', 'Analysis'), ('research', 'Research Discovery'), ('grounding', 'Grounding Inference')], default='chat_message', max_length=20),
        ),
    ]
