# Generated by Django 5.0.1 on 2026-02-01 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('upload', 'Uploaded File'), ('url', 'External URL'), ('text', 'Pasted Text')], max_length=20)),
                ('file_path', models.FileField(blank=True, help_text='Local file path for uploaded documents', null=True, upload_to='documents/')),
                ('file_url', models.CharField(blank=True, help_text='S3 URL for uploads, or external URL', max_length=1000)),
                ('content_text', models.TextField(blank=True, help_text='Extracted text content')),
                ('file_type', models.CharField(blank=True, help_text='pdf, docx, txt, md, etc.', max_length=50)),
                ('file_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('author', models.CharField(blank=True, help_text='Document author', max_length=500)),
                ('published_date', models.DateField(blank=True, help_text='When document was published', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('chunking', 'Chunking'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of chunks created')),
                ('indexed_at', models.DateTimeField(blank=True, help_text='When document was chunked and indexed', null=True)),
                ('user_rating', models.IntegerField(blank=True, help_text="User's credibility rating 1-5 stars", null=True)),
                ('notes', models.TextField(blank=True, help_text="User's notes about this document")),
                ('evidence_count', models.IntegerField(default=0, help_text='Number of evidence items extracted')),
                ('signals_extracted', models.IntegerField(default=0)),
                ('case', models.ForeignKey(blank=True, help_text='Optional: link to specific case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='Order in document (0, 1, 2...)')),
                ('chunk_text', models.TextField(help_text='The actual chunk content')),
                ('token_count', models.IntegerField(help_text='Number of tokens in chunk (using tiktoken)')),
                ('span', models.JSONField(default=dict, help_text='Location info: {page, paragraph, start_char, end_char}')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding (384-dim from sentence-transformers). JSON now, pgvector later at scale', null=True)),
                ('prev_chunk_id', models.UUIDField(blank=True, help_text='Previous chunk ID for context expansion', null=True)),
                ('next_chunk_id', models.UUIDField(blank=True, help_text='Next chunk ID for context expansion', null=True)),
                ('chunking_strategy', models.CharField(choices=[('recursive_token', 'Recursive Token-Based'), ('semantic', 'Semantic Chunking'), ('page_level', 'Page-Level'), ('paragraph', 'Paragraph-Based')], default='recursive_token', help_text='Chunking method used (for experimentation and versioning)', max_length=50)),
                ('vector_id', models.CharField(blank=True, help_text='DEPRECATED: ID in Pinecone/Weaviate (use embedding field instead)', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of chunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='projects.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='The extracted fact or claim')),
                ('type', models.CharField(choices=[('fact', 'Fact'), ('metric', 'Metric/Data Point'), ('claim', 'Claim'), ('quote', 'Direct Quote'), ('benchmark', 'Benchmark Result')], help_text='Type of evidence', max_length=20)),
                ('extraction_confidence', models.FloatField(help_text='How confident the LLM was in this extraction (0.0-1.0)')),
                ('user_credibility_rating', models.IntegerField(blank=True, help_text="User's rating of this evidence (1-5 stars)", null=True)),
                ('embedding', models.JSONField(blank=True, help_text='Semantic embedding (384-dim)', null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(help_text='Chunk this evidence was extracted from', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.documentchunk')),
                ('document', models.ForeignKey(help_text='Document this evidence came from', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.document')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('total_signals', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('top_themes', models.JSONField(blank=True, default=list, help_text='Top 5 themes across project signals')),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='projects_do_documen_79e465_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'prev_chunk_id'], name='projects_do_documen_8c450a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'next_chunk_id'], name='projects_do_documen_0b782f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['vector_id'], name='projects_do_vector__9204b4_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['document', 'type'], name='projects_ev_documen_528219_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['chunk', '-extracted_at'], name='projects_ev_chunk_i_f7c125_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['type', '-extracted_at'], name='projects_ev_type_491ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['document', 'user_credibility_rating'], name='projects_ev_documen_5cdce4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-updated_at'], name='projects_pr_user_id_5d1716_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'is_archived'], name='projects_pr_user_id_1d795e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', '-created_at'], name='projects_do_project_659abf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case', '-created_at'], name='projects_do_case_id_640a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'processing_status'], name='projects_do_user_id_2619db_idx'),
        ),
    ]
