# Generated by Django 5.0.1 on 2026-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='contradicts_signals',
            field=models.ManyToManyField(
                blank=True,
                help_text='Signals this evidence contradicts',
                related_name='contradicted_by_evidence',
                to='signals.signal',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='supports_signals',
            field=models.ManyToManyField(
                blank=True,
                help_text='Signals this evidence supports (provides receipts for)',
                related_name='supported_by_evidence',
                to='signals.signal',
            ),
        ),
    ]
