# Generated by Django 5.0.1 on 2026-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
    ]
