# Generated by Django 5.0.1 on 2026-02-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_add_evidence_signal_links"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentchunk",
            name="projects_do_vector__9204b4_idx",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="vector_id",
        ),
    ]
