# Generated by Django 5.0.1 on 2026-02-07 23:00
# Modified: Evidence model has been removed. Operations cleared.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_deprecated_vector_id_field'),
    ]

    operations = [
        # Evidence model and all its fields have been removed.
        # Original operations added provenance fields to Evidence.
    ]
