# Generated by Django 5.0.1 on 2026-02-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_add_embedding_field'),
        ('projects', '0003_remove_deprecated_vector_id_field'),
        ('signals', '0004_evidence_provenance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='inquiry_evidence',
            field=models.ForeignKey(blank=True, help_text='If bridged from inquiry evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_evidence', to='inquiries.evidence'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='retrieval_method',
            field=models.CharField(choices=[('document_upload', 'Document Upload'), ('research_loop', 'Research Loop'), ('external_paste', 'External Paste'), ('url_fetch', 'URL Fetch'), ('user_observation', 'User Observation'), ('chat_bridged', 'Bridged from Chat Evidence')], default='document_upload', help_text='How this evidence entered the system', max_length=30),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source_domain',
            field=models.CharField(blank=True, help_text='Domain of the source URL', max_length=255),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source_published_date',
            field=models.DateField(blank=True, help_text='Publication date of the source', null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source_title',
            field=models.CharField(blank=True, help_text='Title of the source (article, paper, page)', max_length=500),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL where this evidence was found', max_length=2000),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['source_domain', '-extracted_at'], name='projects_ev_source__8c1191_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['retrieval_method', '-extracted_at'], name='projects_ev_retriev_0e5b8e_idx'),
        ),
    ]
