# Generated by Django 5.0.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('projects', '0004_evidence_provenance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDelta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('snapshot_before', models.JSONField(default=dict, help_text='Case state snapshot taken before document processing')),
                ('snapshot_after', models.JSONField(default=dict, help_text='Case state snapshot taken after document processing')),
                ('delta', models.JSONField(default=dict, help_text='Computed delta: confirms, contradicts, new_information, gaps_remaining, brief_status')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When document processing started', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='When document processing and delta computation finished', null=True)),
                ('case', models.ForeignKey(help_text='The case this document was uploaded to', on_delete=django.db.models.deletion.CASCADE, related_name='document_deltas', to='cases.case')),
                ('document', models.OneToOneField(help_text='The document that was processed', on_delete=django.db.models.deletion.CASCADE, related_name='delta', to='projects.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['case', '-created_at'], name='projects_do_case_id_delta_idx'),
                    models.Index(fields=['status'], name='projects_do_status_delta_idx'),
                ],
            },
        ),
    ]
