# Generated by Django 5.0.1 on 2026-02-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_add_document_delta"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentdelta",
            new_name="projects_do_case_id_835a8f_idx",
            old_name="projects_do_case_id_delta_idx",
        ),
        migrations.RenameIndex(
            model_name="documentdelta",
            new_name="projects_do_status_2e0124_idx",
            old_name="projects_do_status_delta_idx",
        ),
    ]
