# Generated by Django 5.0.1 on 2026-02-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0006_rename_projects_do_case_id_delta_idx_projects_do_case_id_835a8f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_error",
            field=models.TextField(
                blank=True, help_text="Error details if graph extraction failed"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("extracting", "Extracting Nodes"),
                    ("integrating", "Integrating with Graph"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Graph extraction pipeline status",
                max_length=20,
            ),
        ),
    ]
