# Generated by Django 5.0.1 on 2026-02-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_documentdelta_add_processing_progress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='projects_do_project_0e01af_idx',
            old_name='projects_do_project_scope_idx',
        ),
    ]
