# Generated by Django 5.0.1 on 2026-02-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='evidence_count',
        ),
        migrations.RemoveField(
            model_name='document',
            name='signals_extracted',
        ),
    ]
