# Generated by Django 5.0.1 on 2026-02-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_documentchunk_content_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="top_themes",
        ),
        migrations.RemoveField(
            model_name="project",
            name="total_signals",
        ),
    ]
