# Generated by Django 5.0.1 on 2026-02-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_remove_project_top_themes_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentchunk",
            name="projects_do_documen_8c450a_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentchunk",
            name="projects_do_documen_0b782f_idx",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="chunking_strategy",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="next_chunk_id",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="prev_chunk_id",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="summary",
        ),
    ]
