# Generated by Django 5.0.1 on 2026-02-01 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('default_case_view', models.CharField(choices=[('brief', 'Brief'), ('dashboard', 'Dashboard'), ('documents', 'Documents')], default='brief', help_text='Default view when opening a case', max_length=20)),
                ('auto_save_delay_ms', models.IntegerField(default=1000, help_text='Delay in milliseconds before auto-saving (1000 = 1 second)')),
                ('auto_create_inquiries', models.BooleanField(default=True, help_text='Auto-create inquiries from conversation questions')),
                ('auto_detect_assumptions', models.BooleanField(default=True, help_text='Auto-detect assumptions in conversations')),
                ('auto_generate_titles', models.BooleanField(default=True, help_text='Auto-generate titles for cases and inquiries')),
                ('chat_model', models.CharField(default='anthropic:claude-4-5-haiku-20251022', help_text='Preferred model for chat conversations', max_length=100)),
                ('agent_check_interval', models.IntegerField(default=3, help_text='Check for agent inflection points every N turns')),
                ('agent_min_confidence', models.FloatField(default=0.75, help_text='Minimum confidence to suggest agents (0.0-1.0)')),
                ('agent_auto_run', models.BooleanField(default=False, help_text='Auto-run agents when confidence is very high (>0.95)')),
                ('evidence_min_credibility', models.IntegerField(default=3, help_text='Minimum credibility rating for resolution (1-5 stars)')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (system)')], default='light', help_text='UI theme', max_length=10)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Editor font size', max_length=10)),
                ('density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('relaxed', 'Relaxed')], default='comfortable', help_text='UI spacing density', max_length=15)),
                ('email_notifications', models.BooleanField(default=False, help_text='Enable email notifications')),
                ('notify_on_inquiry_resolved', models.BooleanField(default=True, help_text='Notify when inquiry is resolved')),
                ('notify_on_agent_complete', models.BooleanField(default=True, help_text='Notify when agent completes')),
                ('show_debug_info', models.BooleanField(default=False, help_text='Show event IDs, correlation IDs in UI')),
                ('show_ai_prompts', models.BooleanField(default=False, help_text='Show AI prompts for transparency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
