# Generated by Django 5.0.1 on 2026-02-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="chat_model",
            field=models.CharField(
                default="anthropic:claude-haiku-4-5",
                help_text="Preferred model for chat conversations",
                max_length=100,
            ),
        ),
    ]
