# Generated by Django 5.0.1 on 2026-02-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_alter_userpreferences_chat_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="highlight_assumptions",
            field=models.BooleanField(
                default=True, help_text="Highlight assumptions inline in chat"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="highlight_evidence",
            field=models.BooleanField(
                default=True, help_text="Highlight evidence inline in chat"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="highlight_questions",
            field=models.BooleanField(
                default=True, help_text="Highlight questions inline in chat"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="structure_auto_create",
            field=models.BooleanField(
                default=False,
                help_text="Auto-create case in background vs. show suggestion",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="structure_auto_detect",
            field=models.BooleanField(
                default=True,
                help_text="Auto-detect when structure (case/inquiries) would help",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="structure_sensitivity",
            field=models.IntegerField(
                default=3,
                help_text="How quickly to suggest structure (1=conservative, 5=proactive)",
            ),
        ),
    ]
