"""
Companion models - Meta-cognitive reflection and inquiry history tracking
"""
from django.db import models
from apps.common.models import UUIDModel, TimestampedModel


class ReflectionTriggerType(models.TextChoices):
    """What triggered the reflection"""
    USER_MESSAGE = 'user_message', 'User Message'
    DOCUMENT_UPLOAD = 'document_upload', 'Document Upload'
    CONTRADICTION_DETECTED = 'contradiction_detected', 'Contradiction Detected'
    PERIODIC = 'periodic', 'Periodic Reflection'
    CONFIDENCE_CHANGE = 'confidence_change', 'Confidence Change'


class Reflection(UUIDModel, TimestampedModel):
    """
    Natural language meta-commentary generated by the companion.
    
    Stores the "thinking" section content that appears in the reasoning panel.
    Reflections are Socratic - they ask questions, challenge assumptions,
    and help users think more deeply about their conversations.
    """
    thread = models.ForeignKey(
        'chat.ChatThread',
        on_delete=models.CASCADE,
        related_name='reflections',
        help_text="Thread this reflection belongs to"
    )
    
    reflection_text = models.TextField(
        help_text="Natural language meta-commentary (2-3 paragraphs)"
    )
    
    trigger_type = models.CharField(
        max_length=50,
        choices=ReflectionTriggerType.choices,
        help_text="What event triggered this reflection"
    )
    
    # Context tracking - what was analyzed
    analyzed_messages = models.JSONField(
        default=list,
        help_text="List of message IDs that were analyzed"
    )
    
    analyzed_signals = models.JSONField(
        default=list,
        help_text="List of signal IDs that were considered"
    )
    
    # Patterns identified
    patterns = models.JSONField(
        default=dict,
        blank=True,
        help_text="Graph patterns identified (ungrounded, contradictions, etc.)"
    )
    
    # Visibility control
    is_visible = models.BooleanField(
        default=True,
        help_text="Whether to show in companion panel"
    )
    
    # User interaction tracking
    viewed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When user last viewed this reflection"
    )
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['thread', '-created_at']),
            models.Index(fields=['thread', 'is_visible', '-created_at']),
            models.Index(fields=['trigger_type', '-created_at']),
        ]
    
    def __str__(self):
        return f"Reflection for {self.thread.title[:40]} ({self.trigger_type})"


class InquiryHistory(UUIDModel):
    """
    Tracks confidence changes over time for inquiries.
    
    Enables visualization of confidence evolution ("75% → 45%").
    Each time an inquiry's confidence changes, a history entry is created.
    """
    inquiry = models.ForeignKey(
        'inquiries.Inquiry',
        on_delete=models.CASCADE,
        related_name='confidence_history',
        help_text="Inquiry being tracked"
    )
    
    confidence = models.FloatField(
        help_text="Confidence level at this point in time (0.0-1.0)"
    )
    
    # What caused the change
    trigger_event = models.ForeignKey(
        'events.Event',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Event that caused this confidence change"
    )
    
    reason = models.TextField(
        blank=True,
        help_text="Human-readable explanation for the change"
    )
    
    # Timestamp
    timestamp = models.DateTimeField(
        auto_now_add=True,
        help_text="When this confidence level was recorded"
    )
    
    class Meta:
        verbose_name_plural = 'inquiry histories'
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['inquiry', '-timestamp']),
            models.Index(fields=['timestamp']),
        ]
    
    def __str__(self):
        return f"{self.inquiry.title[:40]} @ {int(self.confidence * 100)}% ({self.timestamp.strftime('%Y-%m-%d %H:%M')})"
