# Generated by Django 5.0.1 on 2026-02-01 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('UserMessageCreated', 'User Message Created'), ('AssistantMessageCreated', 'Assistant Message Created'), ('CaseCreated', 'Case Created'), ('CasePatched', 'Case Patched'), ('CaseLinkedToThread', 'Case Linked to Thread'), ('ConversationAnalyzedForCase', 'Conversation Analyzed for Case'), ('CaseCreatedFromAnalysis', 'Case Created from Analysis'), ('InquiriesAutoCreated', 'Inquiries Auto-Created'), ('InquiryCreated', 'Inquiry Created'), ('InquiryResolved', 'Inquiry Resolved'), ('InquiryReopened', 'Inquiry Reopened'), ('InquiryPriorityChanged', 'Inquiry Priority Changed'), ('CaseDocumentCreated', 'Case Document Created'), ('CaseDocumentUpdated', 'Case Document Updated'), ('CaseDocumentDeleted', 'Case Document Deleted'), ('EvidenceCreated', 'Evidence Created'), ('EvidenceUpdated', 'Evidence Updated'), ('ObjectionCreated', 'Objection Created'), ('ObjectionAddressed', 'Objection Addressed'), ('ObjectionDismissed', 'Objection Dismissed'), ('CitationCreated', 'Citation Created'), ('CitationDeleted', 'Citation Deleted'), ('SignalExtracted', 'Signal Extracted'), ('SignalsLinkedToCase', 'Signals Linked to Case'), ('SignalStatusChanged', 'Signal Status Changed'), ('SignalEdited', 'Signal Edited'), ('WorkingViewMaterialized', 'Working View Materialized'), ('WorkflowStarted', 'Workflow Started'), ('WorkflowCompleted', 'Workflow Completed')], db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('case_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('thread_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('can_append_event', 'Can append events')],
                'indexes': [models.Index(fields=['timestamp'], name='events_even_timesta_f18d0e_idx'), models.Index(fields=['case_id', 'timestamp'], name='events_even_case_id_5d742f_idx'), models.Index(fields=['thread_id', 'timestamp'], name='events_even_thread__9d1cb6_idx'), models.Index(fields=['type', 'timestamp'], name='events_even_type_d7304f_idx'), models.Index(fields=['correlation_id'], name='events_even_correla_2f9f43_idx'), models.Index(fields=['actor_type', 'actor_id', 'timestamp'], name='events_even_actor_t_6b6a54_idx')],
            },
        ),
    ]
