# Generated by Django 5.0.1 on 2026-02-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('UserMessageCreated', 'User Message Created'), ('AssistantMessageCreated', 'Assistant Message Created'), ('CaseCreated', 'Case Created'), ('CasePatched', 'Case Patched'), ('CaseLinkedToThread', 'Case Linked to Thread'), ('ConversationAnalyzedForCase', 'Conversation Analyzed for Case'), ('CaseCreatedFromAnalysis', 'Case Created from Analysis'), ('InquiriesAutoCreated', 'Inquiries Auto-Created'), ('InquiryCreated', 'Inquiry Created'), ('InquiryResolved', 'Inquiry Resolved'), ('InquiryReopened', 'Inquiry Reopened'), ('InquiryPriorityChanged', 'Inquiry Priority Changed'), ('CaseDocumentCreated', 'Case Document Created'), ('CaseDocumentUpdated', 'Case Document Updated'), ('CaseDocumentDeleted', 'Case Document Deleted'), ('EvidenceCreated', 'Evidence Created'), ('EvidenceUpdated', 'Evidence Updated'), ('ObjectionCreated', 'Objection Created'), ('ObjectionAddressed', 'Objection Addressed'), ('ObjectionDismissed', 'Objection Dismissed'), ('CitationCreated', 'Citation Created'), ('CitationDeleted', 'Citation Deleted'), ('SignalExtracted', 'Signal Extracted'), ('SignalsLinkedToCase', 'Signals Linked to Case'), ('SignalStatusChanged', 'Signal Status Changed'), ('SignalEdited', 'Signal Edited'), ('WorkingViewMaterialized', 'Working View Materialized'), ('WorkflowStarted', 'Workflow Started'), ('WorkflowCompleted', 'Workflow Completed'), ('ConversationAnalyzedForAgent', 'Conversation Analyzed for Agent'), ('AgentSuggested', 'Agent Suggested'), ('AgentConfirmed', 'Agent Confirmed by User'), ('AgentDeclined', 'Agent Declined by User'), ('AgentWorkflowStarted', 'Agent Workflow Started'), ('AgentProgress', 'Agent Progress Update'), ('AgentCompleted', 'Agent Workflow Completed'), ('AgentFailed', 'Agent Workflow Failed')], db_index=True, max_length=100),
        ),
    ]
