# Generated by Django 5.0.1 on 2026-02-01 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(help_text='Version number (1, 2, 3...)')),
                ('blocks', models.JSONField(help_text='\n        Array of blocks:\n        [\n          {\n            "id": "block_uuid",\n            "type": "heading" | "paragraph" | "list" | "quote" | "citation",\n            "content": "text content",\n            "cites": ["signal_uuid", "evidence_uuid"],\n            "metadata": {...}\n          }\n        ]\n        ')),
                ('diff', models.JSONField(blank=True, default=dict, help_text='\n        Diff from parent version:\n        {\n          "added_blocks": ["block_id", ...],\n          "removed_blocks": ["block_id", ...],\n          "modified_blocks": [\n            {"block_id": "...", "old_content": "...", "new_content": "..."}\n          ]\n        }\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_ms', models.IntegerField(blank=True, help_text='Time to generate (ms)', null=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('research', 'Research Report'), ('critique', 'Critique/Red-team Analysis'), ('brief', 'Decision Brief'), ('deck', 'Presentation Deck')], max_length=20)),
                ('version_count', models.IntegerField(default=1)),
                ('generated_by', models.CharField(help_text='adk_research, adk_critique, adk_brief, or user', max_length=50)),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt used to generate this artifact')),
                ('is_published', models.BooleanField(default=False, help_text='Whether artifact is finalized')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='cases.case')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
