# Generated by Django 5.0.1 on 2026-02-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='artifacts.artifactversion'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artifacts.artifactversion'),
        ),
        migrations.AddIndex(
            model_name='artifactversion',
            index=models.Index(fields=['artifact', '-version'], name='artifacts_a_artifac_0f9218_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactversion',
            index=models.Index(fields=['created_at'], name='artifacts_a_created_941651_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactversion',
            unique_together={('artifact', 'version')},
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['case', '-updated_at'], name='artifacts_a_case_id_91e494_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['user', 'type'], name='artifacts_a_user_id_c64738_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['is_published', '-updated_at'], name='artifacts_a_is_publ_e907bc_idx'),
        ),
    ]
