# Generated by Django 5.0.1 on 2026-02-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_initial'),
        ('skills', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='skills_used',
            field=models.ManyToManyField(blank=True, help_text='Skills that were active during artifact generation', related_name='used_in_artifacts', to='skills.skill'),
        ),
    ]
