# Generated by Django 5.0.1 on 2026-02-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_artifact_skills_used'),
        ('graph', '0006_remove_node_idx_node_case_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='input_nodes',
            field=models.ManyToManyField(blank=True, help_text='Graph nodes (evidence, claims, etc.) that informed this artifact', related_name='used_in_artifacts', to='graph.node'),
        ),
    ]
