# Generated by Django 5.0.1 on 2026-02-08 22:00

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0021_remove_workingview_case_and_more"),
        ("chat", "0006_chatthread_title_manually_edited"),
        ("projects", "0007_document_extraction_error_document_extraction_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable pgvector extension in PostgreSQL
        VectorExtension(),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("claim", "Claim"),
                            ("evidence", "Evidence"),
                            ("assumption", "Assumption"),
                            ("tension", "Tension"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("supported", "Supported"),
                            ("contested", "Contested"),
                            ("unsubstantiated", "Unsubstantiated"),
                            ("confirmed", "Confirmed"),
                            ("uncertain", "Uncertain"),
                            ("disputed", "Disputed"),
                            ("untested", "Untested"),
                            ("assumption_confirmed", "Assumption Confirmed"),
                            ("challenged", "Challenged"),
                            ("refuted", "Refuted"),
                            ("surfaced", "Surfaced"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Human-readable content of this node"),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific metadata (see docstring)",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("project", "Project"), ("case", "Case")],
                        default="project",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("document_extraction", "Document Extraction"),
                            ("chat_edit", "Chat Edit"),
                            ("agent_analysis", "Agent Analysis"),
                            ("user_edit", "User Edit"),
                            ("integration", "Integration"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=384,
                        help_text="384-dim embedding from sentence-transformers all-MiniLM-L6-v2",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.8, help_text="Confidence in this node (0.0-1.0)"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        help_text="If case-scoped, which case owns this node",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graph_nodes",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to="projects.project",
                    ),
                ),
                (
                    "source_chunks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="source_for_nodes",
                        to="projects.documentchunk",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_nodes",
                        to="projects.document",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_nodes",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("supports", "Supports"),
                            ("contradicts", "Contradicts"),
                            ("depends_on", "Depends On"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence in this relationship (0.0-1.0)",
                        null=True,
                    ),
                ),
                (
                    "provenance",
                    models.TextField(
                        blank=True, help_text="Why this relationship exists"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("document_extraction", "Document Extraction"),
                            ("chat_edit", "Chat Edit"),
                            ("agent_analysis", "Agent Analysis"),
                            ("user_edit", "User Edit"),
                            ("integration", "Integration"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.document",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.node",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.node",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GraphDelta",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("document_upload", "Document Upload"),
                            ("chat_edit", "Chat Edit"),
                            ("agent_analysis", "Agent Analysis"),
                            ("user_edit", "User Edit"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "patch",
                    models.JSONField(
                        default=dict,
                        help_text="Structured diff: {nodes_added, nodes_modified, nodes_removed, edges_added, ...}",
                    ),
                ),
                (
                    "narrative",
                    models.TextField(
                        blank=True,
                        help_text="2-3 sentence summary of what changed and why it matters",
                    ),
                ),
                ("nodes_created", models.IntegerField(default=0)),
                ("nodes_updated", models.IntegerField(default=0)),
                ("edges_created", models.IntegerField(default=0)),
                ("tensions_surfaced", models.IntegerField(default=0)),
                ("assumptions_challenged", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_deltas",
                        to="projects.project",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graph_deltas",
                        to="projects.document",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graph_deltas",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="graph_graph_project_e68496_idx",
                    ),
                    models.Index(
                        fields=["trigger"], name="graph_graph_trigger_92d610_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["project", "node_type"], name="graph_node_project_d7f785_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["project", "scope"], name="graph_node_project_135859_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["case", "node_type"], name="graph_node_case_id_b0ffda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["source_document"], name="graph_node_source__b5b4dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["project", "status"], name="graph_node_project_c592d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["source_node", "edge_type"],
                name="graph_edge_source__5bec57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["target_node", "edge_type"],
                name="graph_edge_target__b89439_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["edge_type"], name="graph_edge_edge_ty_c48c04_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("source_node", "target_node", "edge_type"),
                name="unique_edge_per_type",
            ),
        ),
    ]
