# Generated by Django 5.0.1 on 2026-02-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
        ("projects", "0007_document_extraction_error_document_extraction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.document",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_nodes",
                to="projects.document",
            ),
        ),
    ]
