# Generated by Django 5.0.1 on 2026-02-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_casenodereference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casenodereference',
            new_name='graph_casen_case_id_d0b2d7_idx',
            old_name='graph_casen_case_id_excluded_idx',
        ),
        migrations.RenameIndex(
            model_name='casenodereference',
            new_name='graph_casen_node_id_7b42b2_idx',
            old_name='graph_casen_node_id_idx',
        ),
    ]
