# Generated by Django 5.0.1 on 2026-02-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_node_case_scope_idx_graphdelta_case'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='node',
            name='idx_node_case_scope',
        ),
    ]
