# Generated by Django 5.0.1 on 2026-02-09 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0006_remove_node_idx_node_case_scope"),
        (
            "projects",
            "0016_remove_documentchunk_projects_do_documen_8c450a_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "No summary yet"),
                            ("seed", "Seed (template, no LLM)"),
                            ("generating", "Generating"),
                            ("partial", "Partial"),
                            ("full", "Full"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=dict,
                        help_text="Structured sections: overview, key_findings, emerging_picture, attention_needed, what_changed",
                    ),
                ),
                ("is_stale", models.BooleanField(default=False)),
                ("stale_since", models.DateTimeField(blank=True, null=True)),
                ("generation_metadata", models.JSONField(blank=True, default=dict)),
                ("version", models.IntegerField(default=1)),
                ("clusters", models.JSONField(blank=True, default=list)),
                (
                    "latest_delta_at_generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="graph.graphdelta",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="graph_proje_project_81a683_idx",
                    ),
                    models.Index(
                        fields=["project", "is_stale"],
                        name="graph_proje_project_b966d4_idx",
                    ),
                ],
            },
        ),
    ]
