# Generated by Django 5.0.1 on 2026-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0007_projectsummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsummary",
            name="status",
            field=models.CharField(
                choices=[
                    ("none", "No summary yet"),
                    ("seed", "Seed (template, no LLM)"),
                    ("thematic", "Thematic (chunk-based, no graph)"),
                    ("generating", "Generating"),
                    ("partial", "Partial"),
                    ("full", "Full"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
