# Generated by Django 5.0.1 on 2026-02-11 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_clusterhierarchy_projectinsight'),
        ('graph', '0009_projectsummary_project_status_idx'),
        ('projects', '0016_remove_documentchunk_projects_do_documen_8c450a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdelta',
            name='trigger',
            field=models.CharField(choices=[('document_upload', 'Document Upload'), ('chat_edit', 'Chat Edit'), ('agent_analysis', 'Agent Analysis'), ('user_edit', 'User Edit'), ('case_extraction', 'Case Extraction')], max_length=32),
        ),
        migrations.CreateModel(
            name='ClusterHierarchy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='building', max_length=20)),
                ('tree', models.JSONField(default=dict, help_text='Serialized ClusterTreeNode tree: {id, level, label, summary, children, chunk_ids, ...}')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Generation metadata: model, duration_ms, total_chunks, total_clusters, levels')),
                ('is_current', models.BooleanField(default=True, help_text='Only the latest successful hierarchy should be current')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_hierarchies', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='graph_clust_project_6dd04d_idx'), models.Index(fields=['project', 'is_current'], name='graph_hierarchy_current_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectInsight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('tension', 'Tension'), ('blind_spot', 'Blind Spot'), ('pattern', 'Pattern'), ('stale_finding', 'Stale Finding'), ('connection', 'Connection')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('agent_discovery', 'Agent Discovery'), ('case_promotion', 'Case Promotion'), ('user_created', 'User Created')], default='agent_discovery', max_length=20)),
                ('source_cluster_ids', models.JSONField(blank=True, default=list, help_text='Cluster tree node IDs involved in this insight')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('confidence', models.FloatField(default=0.7, help_text="Agent's confidence in this insight (0.0-1.0)")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Generation metadata: model, prompt_tokens, etc.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='projects.project')),
                ('source_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_insights', to='cases.case')),
                ('source_chunks', models.ManyToManyField(blank=True, help_text='Evidence chunks supporting this insight', to='projects.documentchunk')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='graph_proje_project_423bc7_idx'), models.Index(fields=['project', 'insight_type'], name='graph_proje_project_c9910c_idx'), models.Index(fields=['project', '-created_at'], name='graph_proje_project_ed3057_idx')],
            },
        ),
    ]
