# Generated by Django 5.0.1 on 2026-02-14 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0026_alter_case_status_decisionrecord"),
        ("chat", "0008_message_source_chunks"),
        ("graph", "0010_clusterhierarchy_projectinsight"),
        (
            "projects",
            "0016_remove_documentchunk_projects_do_documen_8c450a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinsight",
            name="action_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Exit ramp action: 'discuss', 'research', or '' for none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectinsight",
            name="display_order",
            field=models.IntegerField(
                default=0, help_text="Ordering within an orientation (lower = first)"
            ),
        ),
        migrations.AddField(
            model_name="projectinsight",
            name="linked_thread",
            field=models.ForeignKey(
                blank=True,
                help_text="Chat thread opened via 'Discuss this' action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_insights",
                to="chat.chatthread",
            ),
        ),
        migrations.AddField(
            model_name="projectinsight",
            name="research_result",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Background research findings: {answer, sources[], researched_at}",
            ),
        ),
        migrations.AlterField(
            model_name="projectinsight",
            name="insight_type",
            field=models.CharField(
                choices=[
                    ("tension", "Tension"),
                    ("blind_spot", "Blind Spot"),
                    ("pattern", "Pattern"),
                    ("stale_finding", "Stale Finding"),
                    ("connection", "Connection"),
                    ("consensus", "Consensus"),
                    ("gap", "Gap"),
                    ("weak_evidence", "Weak Evidence"),
                    ("exploration_angle", "Exploration Angle"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectinsight",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("agent_discovery", "Agent Discovery"),
                    ("case_promotion", "Case Promotion"),
                    ("user_created", "User Created"),
                    ("orientation", "Orientation"),
                ],
                default="agent_discovery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectinsight",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("superseded", "Superseded"),
                    ("researching", "Researching"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectOrientation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                (
                    "lens_type",
                    models.CharField(
                        help_text="Primary lens: positions_and_tensions, structure_and_dependencies, perspectives_and_sentiment, obligations_and_constraints, events_and_causation, concepts_and_progression",
                        max_length=40,
                    ),
                ),
                (
                    "lead_text",
                    models.TextField(
                        blank=True,
                        help_text="2-3 sentence lead paragraph orienting the user.",
                    ),
                ),
                (
                    "lens_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Scores for each candidate lens: {lens_type: float}",
                    ),
                ),
                (
                    "secondary_lens",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Secondary lens type (surfaced as invitation, not auto-applied)",
                        max_length=40,
                    ),
                ),
                (
                    "secondary_lens_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why the secondary lens is relevant (1 sentence)",
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Timing, model, token counts, etc.",
                    ),
                ),
                (
                    "hierarchy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orientations",
                        to="graph.clusterhierarchy",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="projectinsight",
            name="orientation",
            field=models.ForeignKey(
                blank=True,
                help_text="Which orientation generated this insight (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="graph.projectorientation",
            ),
        ),
        migrations.AddIndex(
            model_name="projectinsight",
            index=models.Index(
                fields=["orientation", "display_order"],
                name="graph_proje_orienta_578191_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectorientation",
            index=models.Index(
                fields=["project", "-created_at"], name="graph_proje_project_a48a03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectorientation",
            index=models.Index(
                fields=["project", "is_current"], name="graph_orientation_current_idx"
            ),
        ),
    ]
