# Generated by Django 5.0.1 on 2026-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_project_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectorientation',
            name='generation_context',
            field=models.JSONField(blank=True, default=dict, help_text='Context that influenced this generation: source, thread_id, user_message, etc.'),
        ),
        migrations.AddField(
            model_name='projectorientation',
            name='user_guidance',
            field=models.TextField(blank=True, help_text='User-supplied perspective or emphasis that influenced lens selection and synthesis.', null=True),
        ),
    ]
