# Generated by Django 5.0.1 on 2026-02-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0013_projectinsight_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinsight",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("agent_discovery", "Agent Discovery"),
                    ("case_promotion", "Case Promotion"),
                    ("conversation_promotion", "Conversation Promotion"),
                    ("user_created", "User Created"),
                    ("orientation", "Orientation"),
                ],
                default="agent_discovery",
                max_length=30,
            ),
        ),
    ]
