# Generated by Django 5.0.1 on 2026-02-01 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(help_text="Question or claim being investigated (e.g., 'Is PostgreSQL faster for our write workload?')")),
                ('description', models.TextField(blank=True, help_text='Additional context about this inquiry')),
                ('created_from_event_id', models.UUIDField(blank=True, help_text='Event that created this inquiry (for provenance)', null=True)),
                ('origin_text', models.TextField(blank=True, help_text='Selected text from document that sparked this inquiry', null=True)),
                ('text_span', models.JSONField(blank=True, help_text='Character range in origin document: {from, to, section}', null=True)),
                ('elevation_reason', models.CharField(choices=[('repetition', 'Repeated Signal'), ('conflict', 'Conflicting Signals'), ('blocking', 'Blocks Decision'), ('user_created', 'User Promoted'), ('high_strength', 'High Signal Strength')], help_text='What triggered the creation of this inquiry', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='open', max_length=20)),
                ('conclusion', models.TextField(blank=True, help_text='Final conclusion or answer to the inquiry')),
                ('conclusion_confidence', models.FloatField(blank=True, help_text='Confidence in conclusion 0.0-1.0', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the inquiry was resolved', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher = more important. 0 = normal priority')),
                ('sequence_index', models.IntegerField(help_text='Order inquiry was created in case (0, 1, 2...)')),
                ('brief', models.ForeignKey(blank=True, help_text='Inquiry-level brief document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_brief_for_inquiry', to='cases.casedocument')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='cases.case')),
                ('origin_document', models.ForeignKey(blank=True, help_text='Document where the inquiry originated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_inquiries', to='cases.casedocument')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-priority', 'sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('document_full', 'Whole Document'), ('document_chunks', 'Document Section'), ('experiment', 'Experiment/Test'), ('external_data', 'External Data'), ('user_observation', 'User Observation')], max_length=50)),
                ('evidence_text', models.TextField(help_text="User's interpretation or direct quote")),
                ('direction', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('neutral', 'Neutral/Context')], max_length=20)),
                ('strength', models.FloatField(default=0.5, help_text='How strong is this evidence (0.0-1.0)')),
                ('credibility', models.FloatField(default=0.5, help_text='How credible is the source (0.0-1.0)')),
                ('verified', models.BooleanField(default=False, help_text='User has verified this evidence')),
                ('notes', models.TextField(blank=True, help_text="User's notes about this evidence")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_evidence', to=settings.AUTH_USER_MODEL)),
                ('source_chunks', models.ManyToManyField(blank=True, related_name='evidence_uses', to='projects.documentchunk')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_uses', to='projects.document')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='inquiries.inquiry')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objection_text', models.TextField(help_text='The challenge or alternative perspective')),
                ('objection_type', models.CharField(choices=[('alternative_perspective', 'Alternative Perspective'), ('challenge_assumption', 'Challenge Assumption'), ('counter_evidence', 'Counter Evidence'), ('scope_limitation', 'Scope Limitation'), ('missing_consideration', 'Missing Consideration')], max_length=50)),
                ('source', models.CharField(choices=[('system', 'System Generated'), ('user', 'User Created'), ('document', 'From Document')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('addressed', 'Addressed'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('addressed_how', models.TextField(blank=True, help_text='How this objection was resolved or addressed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_objections', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='inquiries.inquiry')),
                ('source_chunks', models.ManyToManyField(blank=True, related_name='objection_sources', to='projects.documentchunk')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objection_sources', to='projects.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['case', 'status'], name='inquiries_i_case_id_3616fc_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['case', 'priority', 'status'], name='inquiries_i_case_id_58f761_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['case', 'sequence_index'], name='inquiries_i_case_id_47e2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'created_at'], name='inquiries_i_status_38a868_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['inquiry', 'direction'], name='inquiries_e_inquiry_2f60ab_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['source_document'], name='inquiries_e_source__920502_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['created_by', '-created_at'], name='inquiries_e_created_982b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['inquiry', 'status'], name='inquiries_o_inquiry_407fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['source_document'], name='inquiries_o_source__407af6_idx'),
        ),
        migrations.AddIndex(
            model_name='objection',
            index=models.Index(fields=['created_by', '-created_at'], name='inquiries_o_created_d46529_idx'),
        ),
    ]
