# Generated by Django 5.0.1 on 2026-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0002_inquiry_blocked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Pre-computed embedding vector for semantic search",
                null=True,
            ),
        ),
    ]
