# Generated by Django 5.0.1 on 2026-02-09 01:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_type'),
        ('inquiries', '0003_add_embedding_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(help_text='Confidence level at this point in time (0.0-1.0)')),
                ('reason', models.TextField(blank=True, help_text='Human-readable explanation for the change')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this confidence level was recorded')),
                ('inquiry', models.ForeignKey(help_text='Inquiry being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='confidence_history', to='inquiries.inquiry')),
                ('trigger_event', models.ForeignKey(blank=True, help_text='Event that caused this confidence change', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'verbose_name_plural': 'inquiry histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.AddIndex(
            model_name='inquiryhistory',
            index=models.Index(fields=['inquiry', '-timestamp'], name='inquiries_i_inquiry_28c515_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiryhistory',
            index=models.Index(fields=['timestamp'], name='inquiries_i_timesta_f1a126_idx'),
        ),
    ]
