# Generated by Django 5.0.1 on 2026-02-01 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0002_add_evidence_signal_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team'), ('organization', 'Organization'), ('public', 'Public')], default='personal', help_text='Visibility and permission scope', max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('applies_to_agents', models.JSONField(default=list)),
                ('episteme_config', models.JSONField(default=dict)),
                ('current_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('can_edit', models.ManyToManyField(blank=True, help_text='Users who can edit this skill', related_name='editable_skills', to=settings.AUTH_USER_MODEL)),
                ('can_view', models.ManyToManyField(blank=True, help_text='Users who can view this skill', related_name='viewable_skills', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL)),
                ('forked_from', models.ForeignKey(blank=True, help_text='Skill this was forked from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='skills.skill')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='common.organization')),
                ('owner', models.ForeignKey(help_text='Primary owner of this skill', on_delete=django.db.models.deletion.CASCADE, related_name='owned_skills', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team this skill belongs to (for team-scoped skills)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_skills', to='projects.project')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('skill_md_content', models.TextField()),
                ('resources', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_versions', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_versions',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['scope', 'status'], name='skills_scope_34e3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['owner', 'scope'], name='skills_owner_i_4266d5_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['organization', 'scope'], name='skills_organiz_d45268_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('owner', 'name', 'scope')},
        ),
        migrations.AlterUniqueTogether(
            name='skillversion',
            unique_together={('skill', 'version')},
        ),
    ]
