# Generated by Django 5.0.1 on 2026-02-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_active_skills_case_based_on_skill_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='source_case',
            field=models.ForeignKey(blank=True, help_text='Case this skill was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_skills', to='cases.case'),
        ),
    ]
