# Generated by Django 5.0.1 on 2026-02-07 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("skills", "0002_skill_source_case"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillPack",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("organization", "Organization"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon identifier", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_skill_packs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_packs",
                        to="common.organization",
                    ),
                ),
            ],
            options={
                "db_table": "skill_packs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SkillPackMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("domain", "Domain Knowledge"),
                            ("methodology", "Research Methodology"),
                            ("quality", "Quality Standards"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skillpack",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skills.skill"
                    ),
                ),
            ],
            options={
                "db_table": "skill_pack_memberships",
                "ordering": ["order"],
                "unique_together": {("pack", "skill")},
            },
        ),
        migrations.AddField(
            model_name="skillpack",
            name="skills",
            field=models.ManyToManyField(
                related_name="packs",
                through="skills.SkillPackMembership",
                to="skills.skill",
            ),
        ),
    ]
