# Generated by Django 5.0.1 on 2026-02-08 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_remove_workingview_case_and_more"),
        ("common", "0001_initial"),
        ("skills", "0003_skill_packs_and_ordered_active_skills"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillpack",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="skillpack",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="skillpack",
            name="skills",
        ),
        migrations.AlterUniqueTogether(
            name="skillpackmembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="skillpackmembership",
            name="pack",
        ),
        migrations.RemoveField(
            model_name="skillpackmembership",
            name="skill",
        ),
        migrations.AlterUniqueTogether(
            name="skillversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="skillversion",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="skillversion",
            name="skill",
        ),
        migrations.RemoveIndex(
            model_name="skill",
            name="skills_scope_34e3eb_idx",
        ),
        migrations.RemoveIndex(
            model_name="skill",
            name="skills_owner_i_4266d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="skill",
            name="skills_organiz_d45268_idx",
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("owner", "name")},
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_md_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full SKILL.md content with YAML frontmatter",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["status"], name="skills_status_c09232_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["owner"], name="skills_owner_i_354010_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["organization"], name="skills_organiz_70fde7_idx"
            ),
        ),
        migrations.DeleteModel(
            name="SkillPack",
        ),
        migrations.DeleteModel(
            name="SkillPackMembership",
        ),
        migrations.DeleteModel(
            name="SkillVersion",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="can_view",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="current_version",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="forked_from",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="team",
        ),
    ]
