# Generated by Django 5.0.1 on 2026-02-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='last_agent_check_at',
            field=models.DateTimeField(blank=True, help_text='Last time thread was analyzed for agent needs', null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='last_suggested_agent',
            field=models.CharField(blank=True, help_text='Last agent type suggested (research/critique/brief)', max_length=20),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible storage for pending agents, suggestions, etc.'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='turns_since_agent_check',
            field=models.IntegerField(default=0, help_text='User message count since last agent check'),
        ),
    ]
