# Generated by Django 5.0.1 on 2026-02-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_add_thread_type"),
        ("chat", "0002_chatthread_last_agent_check_at_and_more"),
    ]

    operations = []
