# Generated by Django 5.0.1 on 2026-01-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_archived_project_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='chars_since_extraction',
            field=models.IntegerField(default=0, help_text='Character count accumulated since last extraction'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='last_extraction_at',
            field=models.DateTimeField(blank=True, help_text='Last time signals were extracted from this thread', null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='turns_since_extraction',
            field=models.IntegerField(default=0, help_text='User message count since last extraction'),
        ),
    ]
