# Generated by Django 5.0.1 on 2026-02-01 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '__first__'),
        ('chat', '0003_add_extraction_batching'),
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatthread',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='chatthread',
            name='chat_chatth_user_id_7ce1c4_idx',
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['user', '-updated_at'], name='chat_chatth_user_id_d83b7d_idx'),
        ),
    ]
