# Generated by Django 5.0.1 on 2026-02-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_rich_message_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_content_dc73a7_idx',
            old_name='chat_messag_content_idx',
        ),
    ]
