# Generated by Django 5.0.1 on 2026-02-11 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatthread_title_manually_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Plain Text"),
                    ("card_signal_extraction", "Signal Extraction Card"),
                    ("card_case_suggestion", "Case Suggestion Card"),
                    ("card_structure_preview", "Structure Preview Card"),
                    ("card_research_status", "Research Status Card"),
                    ("card_evidence_map", "Evidence Map Card"),
                    ("card_action_prompt", "Action Prompt Card"),
                    ("card_assumption_validator", "Assumption Validator Card"),
                    ("card_research_finding", "Research Finding Card"),
                ],
                default="text",
                help_text="Type of message content (text or card)",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ConversationStructure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "structure_type",
                    models.CharField(
                        help_text="e.g. decision_tree, checklist, comparison, exploration_map, flow, constraint_list, pros_cons, concept_map",
                        max_length=30,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                (
                    "established",
                    models.JSONField(
                        default=list,
                        help_text="Confirmed facts/constraints from the conversation",
                    ),
                ),
                (
                    "open_questions",
                    models.JSONField(
                        default=list,
                        help_text="Unresolved questions (explicit and implicit)",
                    ),
                ),
                (
                    "eliminated",
                    models.JSONField(
                        default=list,
                        help_text="Eliminated options/branches with reasons",
                    ),
                ),
                (
                    "context_summary",
                    models.TextField(
                        default="",
                        help_text="Compact text version for injecting into chat prompt",
                    ),
                ),
                ("last_message_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="chat.chatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["thread", "-version"],
                        name="chat_conver_thread__04783e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResearchResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(default="")),
                ("sources", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("researching", "Researching"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="researching",
                        max_length=20,
                    ),
                ),
                ("surfaced", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_results",
                        to="chat.chatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["thread", "-created_at"],
                        name="chat_resear_thread__56131f_idx",
                    ),
                    models.Index(
                        fields=["thread", "status"],
                        name="chat_resear_thread__7d1c0f_idx",
                    ),
                ],
            },
        ),
    ]
