# Generated by Django 5.0.1 on 2026-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_add_conversation_structure_and_research"),
        (
            "projects",
            "0016_remove_documentchunk_projects_do_documen_8c450a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="source_chunks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Document chunks used as RAG context for this response",
                related_name="cited_in_messages",
                to="projects.documentchunk",
            ),
        ),
    ]
