# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_message_source_chunks"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationstructure",
            name="rolling_digest",
            field=models.TextField(
                blank=True,
                default="",
                help_text="LLM-generated summary of messages beyond the recent window",
            ),
        ),
    ]
